### PR TITLE
Do not return invalid aggregates from repository

### PR DESCRIPTION
**Pull request by sebastianstucke87**
`\EventSauce\MessageRepository\DoctrineMessageRepository\DoctrineUuidV4MessageRepository::retrieveAllAfterVersion` and `\EventSauce\MessageRepository\DoctrineMessageRepository\DoctrineUuidV4MessageRepository::paginate` might be affected as well, but I'm not sure.

### CODE REVIEW

**Comment by frankdejonge** [comment]
An empty set is still a valid set. What situation are you trying to protect against?

**Comment by sebastianstucke87** [comment]
> An empty set is still a valid set. What situation are you trying to protect against?

When the repository returns an aggregate for an ID which does not exist in the database, then the aggregate was created outside any invariants the application might have. The creation of aggregates is part of the domain, not the infrastructure: the technical detail of constructing and reconstituting an aggregate within the repository is just that, a technical detail.

Querying an ID that does not exist should result in either an empty result (**null**) or in an **exception**:  returning a full-fledged and ready-to-go aggregate suggest that the aggregate actually exists in the DB (which is not the case).

Just to give an example :
- `PATCH /api/user/<USER-ID>`
- `DELETE /api/user/<USER-ID>`

In both cases, the application should return a 404 when the resource does not exist. Of course this can be done within the aggregate (e.g. by calling something like "ensureCanBeModified") resulting in a lot of unnecessary overhead...

**Comment by frankdejonge** [comment]
The behaviour you describe is already possible by using [AggregateRootBehaviourWithRequiredHistory](https://github.com/EventSaucePHP/EventSauce/blob/main/src/AggregateRootBehaviourWithRequiredHistory.php) trait. I personally do prefer to even get an aggregate returned even if there are no events.

**Comment by sebastianstucke87** [comment]
Oh wow, that looks just like my current userland workaround 😅 I had no idea.. Thank you!

**Pull request closed without merging**
